### PR TITLE
Support Swift 5.5

### PR DESCRIPTION
**Pull request by taji-taji**
## Background
When I ran `swift build -c release` on Swift 5.5, I got a compilation error.

## What I did.
- Changed SwiftSyntax version to work with Swift 5.5
- Also, the ArgumentParser in swift-tools-support-core is deprecated, so now it uses swift-argument-parser

### CODE REVIEW

**Review by EspressoCup — APPROVED** [review]

**Comment by EspressoCup** [comment]
thanks for the fix 👍
